DM-27141: General improvements and documentation of ts_cycle_build
lsst-ts/ts_cycle_build pull request #14
Opened 2020-10-24 05:27 UTC by tribeiro

Starting to write documentation for the package in project format.
Update Jenkinsfile.cycle to allow building components using Jenkins server.
Update cycle build to 0015.

2020-10-27 20:49 UTC, mareuter requested changes
- A few questions and some wordsmithing in the text
- Using the revision is discussed in the docs but not implemented in the code. Is this correct?
- We should clearly delineate what are core packages and what is not. I'm not clear on whether or not the stack version necessitates a cycle build.
- We should put the packages the necessitate a new cycle build near the head of the cycle.env file and clearly comment this fact.

2020-10-27 20:49 UTC, mareuter commented on doc/user-guide/user-guide.rst
> +There are two ways users can run a build; manually on a private server or using Jenkins server.
replace "Jenkins server" with "the TSSW Jenkins server". Add a link to the Jenkins page too.

2020-10-27 20:49 UTC, mareuter commented on doc/user-guide/user-guide.rst
> +Since the build requires credentials for the nexus servers, both to access the licensed version of OpenSplice and to pull/push images to the nexus docker registry, it is advisable to use the Jenkins
Add TSSW in front of Jenkins in this sentence.

2020-10-27 20:49 UTC, mareuter commented on doc/user-guide/user-guide.rst
> +  We are investigating ways of automating the process so users that have to worry about setting them up.
replace "so users that" with "so users don't"

2020-10-27 20:49 UTC, mareuter commented on doc/user-guide/user-guide.rst
> +If any of the :ref:`core packages <Core-packages>` version is updated, the cycle number must be incremented, otherwise just increment the revision number and updade the software versions.
change "updade" to "update"

2020-10-27 20:49 UTC, mareuter commented on doc/user-guide/user-guide.rst
> +These steps are designed to maximized reusability of docker layer, minimizing the number of layers in the image and reducing the time it takes to build the system.
replace "docker layer" with "docker layers"

2020-10-27 20:49 UTC, mareuter commented on doc/version-history.rst
> +Release of salobj 6/sal 5 with xml 6.2.0.
Bump to 6.2.1.

2020-10-27 20:49 UTC, mareuter commented on doc/user-guide/user-guide.rst
> +The steps in the build are as follows:
This doesn't look like all of the components are listed here. Do we want to put the list here? Is it better to just point at the Jenkinsfile for this?

2020-10-28 21:42 UTC, tribeiro commented on doc/user-guide/user-guide.rst
> +In general this problem can be avoided by use of loosely typed topics and schema evolution, which allows readers and writers to exchange any type of data structure and translate different versions.
I think it is possible... we could have a single "payload" attribute which is a json string that is parsed around..  I think this is sort of what we do with kafka and Avro on the EFD side. kafka itself does not have schema evolution or anything like that, we use Avro for that part.

2020-10-28 21:56 UTC, tribeiro commented on Jenkinsfile.cycle
> +              docker-compose --env-file cycle/cycle.env -f cycle/docker-compose.yaml build ataos atdome atdometrajectory athexapod atmcs_sim atpneumatics_sim atspectrograph hexapod mtdome mtdometraje
This is a great idea. Do you mind if I implement it in DM-26305 instead? Don't want to create merge conflicts if I can avoid them... :)

2020-10-28 22:00 UTC, tribeiro commented
I implemented most of your suggestions. Responding to your review questions:

- Using the revision is discussed in the docs but not implemented in the code. Is this correct?
  - Yes. I am still looking at a good way to implement it. 

- We should clearly delineate what are core packages and what is not. I'm not clear on whether or not the stack version necessitates a cycle build.
  - At this time I was assuming only our core packages would could for the cycle count. So the dm stack could be a revision. But I can see arguments for both. So, maybe something we will have to figure out in the field?

- We should put the packages the necessitate a new cycle build near the head of the cycle.env file and clearly comment this fact.
  - Yes, that is what I current have. I will make a comment on cycle.env about that. But I'd rather do it in DM-27305 if you don't mind. Just to avoid merge conflicts.

2020-10-28 22:19 UTC, mareuter commented on doc/user-guide/user-guide.rst
> +In general this problem can be avoided by use of loosely typed topics and schema evolution, which allows readers and writers to exchange any type of data structure and translate different versions.
Interesting idea. There's quite a loss of clarity in what payload means without schema validation being used.

2020-10-28 22:20 UTC, mareuter commented on doc/user-guide/user-guide.rst
> +The steps in the build are as follows:
OK. I think that looks like everyone.

2020-10-28 22:22 UTC, mareuter commented
>     * We should put the packages the necessitate a new cycle build near the head of the cycle.env file and clearly comment this fact.
>       
>       * Yes, that is what I current have. I will make a comment on cycle.env about that. But I'd rather do it in DM-27305 if you don't mind. Just to avoid merge conflicts.

#

2020-10-28 22:23 UTC, tribeiro commented on doc/user-guide/user-guide.rst
> +In general this problem can be avoided by use of loosely typed topics and schema evolution, which allows readers and writers to exchange any type of data structure and translate different versions.
yes... it would make the topics completely opaque.... not suggesting we do it, just saying it is possible...

2020-10-28 22:25 UTC, mareuter approved these changes
Thanks for the updates. We can wait on the cycle.env work until a more convenient time. PR approved.

2020-10-28 22:26 UTC, merged