tickets/DM 40775
lsst-ts/ts_cycle_build pull request #211
Opened 2023-09-22 11:28 UTC by couger01

- Cycle 32 Revision 4
- In rapid analysis build, install rubin-libradtran.
- In rapid analysis build, add environment variables to limit the number of threads/processes used by pipeline tasks to 1 and to set the MPL backend to Agg.
- DM-40660: Add audio_broadcaster to cycle build
- DM-39426: Add oods to cycle build
- DM-39427: Add HeaderService to cycle build
- Update version history

2023-09-22 12:49 UTC, wvreeven approved these changes
Looks good to me.

2023-09-22 14:39 UTC, mareuter commented
We don't need the `atheaderservice` and `ccheaderservice` specific builds. The base one server all our needs.

2023-09-22 15:12 UTC, wvreeven requested changes
Please re-request my review when you're done with the latest changes.

2023-09-22 15:25 UTC, wvreeven submitted a review, later dismissed
Please remove the two env vars as indicated.

2023-09-22 15:25 UTC, wvreeven commented on build/audio_broadcaster/Dockerfile
> +ENV MICROPHONE_SERVER_PORT 4444
These two env vars need to be defined at deploy time so remove them here.

2023-09-22 16:04 UTC, tribeiro reviewed
I have some additional comments. I think there are some extra files in the header service that can be removed. It is a bit confusing to have those files added as it gives the impression they are being used instead of the correct ones you actually use.

2023-09-22 16:04 UTC, tribeiro commented on build/headerservice/setup_HeaderService.env
Is this file being used at all? I think you can remove it no?

2023-09-22 16:04 UTC, tribeiro commented on build/headerservice/Dockerfile
> +COPY start_ATHeaderService.sh /home/saluser/
Is this file needed at all?

2023-09-22 16:04 UTC, tribeiro commented on build/headerservice/Dockerfile
> +COPY start_CCHeaderService.sh /home/saluser/
Is this file needed?

2023-09-22 16:04 UTC, tribeiro commented on build/headerservice/start_ATHeaderService.sh
I think you can remove this file

2023-09-22 16:04 UTC, tribeiro commented on build/headerservice/start_CCHeaderService.sh
I think you can remove this file

2023-09-25 15:44 UTC, tribeiro approved these changes
Looks good!

2023-09-25 16:03 UTC, merged